// <auto-generated />
using System;
using InboxOutboxSample.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InboxOutboxSample.Migrations.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20251012191005_AddEventDetailsToInboxMessage")]
    partial class AddEventDetailsToInboxMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FrameBox.Core.Inbox.Models.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailurePayload")
                        .HasColumnType("text");

                    b.Property<string>("HandlerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("State");

                    b.ToTable("InboxMessages", "FrameBox");
                });

            modelBuilder.Entity("FrameBox.Core.Outbox.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProcessId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("State");

                    b.ToTable("OutboxMessages", "FrameBox");
                });

            modelBuilder.Entity("FrameBox.Storage.EFCore.EventContexts.Models.EventContextDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("EventContexts", "FrameBox");
                });

            modelBuilder.Entity("InboxOutboxSample.ApiService.Domain.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("FrameBox.Storage.EFCore.EventContexts.Models.EventContextDbModel", b =>
                {
                    b.OwnsMany("FrameBox.Storage.EFCore.EventContexts.Models.EventContextEventLink", "LinkedEvents", b1 =>
                        {
                            b1.Property<Guid>("EventContextId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid");

                            b1.HasKey("EventContextId", "EventId");

                            b1.ToTable("EventContexts_Links", "FrameBox");

                            b1.WithOwner()
                                .HasForeignKey("EventContextId");
                        });

                    b.Navigation("LinkedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
