name: FrameBox.MessageBroker.RabbitMQ Package Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/framebox/FrameBox.MessageBroker.RabbitMQ/**'
      - 'pipelines/framebox/framebox-messagebroker-rabbitmq.yml'
      - 'pipelines/framebox/templates/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/framebox/FrameBox.MessageBroker.RabbitMQ/**'
      - 'pipelines/framebox/framebox-messagebroker-rabbitmq.yml'
      - 'pipelines/framebox/templates/**'
  workflow_dispatch:
    inputs:
      force-publish:
        description: 'Force publish to NuGet even on non-main branch'
        required: false
        type: boolean
        default: false

jobs:
  build-and-test:
    uses: ./.github/workflows/dotnet-package.yml
    with:
      project-path: 'src/framebox/FrameBox.MessageBroker.RabbitMQ/FrameBox.MessageBroker.RabbitMQ.csproj'
      package-name: 'FrameBox.MessageBroker.RabbitMQ'
      dotnet-version: '9.0.x'
      run-tests: false  # No tests currently exist
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}