name: FrameBox.Core Package Pipeline

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/framebox/FrameBox.Core/**'
      - 'pipelines/framebox/framebox-core.yml'
      - 'pipelines/framebox/templates/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/framebox/FrameBox.Core/**'
      - 'pipelines/framebox/framebox-core.yml'
      - 'pipelines/framebox/templates/**'
  workflow_dispatch:
    inputs:
      force-publish:
        description: 'Force publish to NuGet even on non-main branch'
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-test:
    uses: ./.github/workflows/dotnet-package.yml
    with:
      project-path: 'src/framebox/FrameBox.Core/FrameBox.Core.csproj'
      package-name: 'FrameBox.Core'
      dotnet-version: '9.0.x'
      run-tests: false  # No tests currently exist
      force-publish: ${{ inputs.force-publish || false }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}